POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "id": "fcd59fa6-c4b4-4fec-ac4d-df4fe1f85f62",
  "date": "2019-09-10",
  "specialist": "MD House",
  "type": "OccupationalHealthcare",
  "employerName": "FBI",
  "description": "Prescriptions renewed once again!"
}